"""add user age

Revision ID: 783d2b197e16
Revises: a97441a98a45
Create Date: 2026-04-16 11:18:52.521009
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '783d2b197e16'
down_revision = 'a97441a98a45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
