"""add user age

Revision ID: a97441a98a45
Revises: e19d54cb5dc5
Create Date: 2026-04-16 11:17:50.782865
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a97441a98a45'
down_revision = 'e19d54cb5dc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
