"""add user age

Revision ID: e19d54cb5dc5
Revises: f2acba2f2eb7
Create Date: 2026-04-16 11:17:03.654210
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e19d54cb5dc5'
down_revision = 'f2acba2f2eb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
