"""...

Revision ID: f2acba2f2eb7
Revises: c002369c8dc2
Create Date: 2026-04-16 09:43:24.293924
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f2acba2f2eb7'
down_revision = 'c002369c8dc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
